### ISSUE TITLE
Fix broken links after merge

### ISSUE THREAD

**Issue by silvioprog** [risoflora/brookfreepascal#1]
Hello,

all links broken after merging the repository from the [old origin](https://github.com/silvioprog/brookframework) will be fixed.
![brook_hello-world](https://user-images.githubusercontent.com/1456829/51649574-cd69d800-1f63-11e9-83ed-111a7cd19d79.png)
![brook_new-project](https://user-images.githubusercontent.com/1456829/51649575-cd69d800-1f63-11e9-878d-5191b74faf77.png)

**Comment by Al-Muhandis** [comment]
Hello! 
Corrected information on the wiki of [FreePascal](http://wiki.freepascal.org/Brook_Framework). See if I got it right?

**Comment by silvioprog** [comment]
Hello @Al-Muhandis , thanks for the adjustments. I'm going to do some merges this week. :-)

**Comment by silvioprog** [comment]
> I'm going to do some merges this week. :-)

Done!
