### ISSUE TITLE
Can I suggest a pullrequest/feature for dOPF plugin?

### ISSUE THREAD

**Issue by Al-Muhandis** [risoflora/brookfreepascal#10]
The problem I'm facing is that in the MySQL database I couldn't use a field with "order" name. Because that field name is a reserved keyword. However, its use is possible in the case of a quoted (`) field name. Unfortunately, different DB can use different quote character so this needs to be done optionally or/and cusomizably. 

Can you consider this [pullrequest](https://github.com/risoflora/brookfreepascal/tree/Al-Muhandis-patch-1) ? The dOPF fork in this form I already use and tested. Addionally there is an idea to make isolation of quotes simply obligatory... Maybe possible to create all SQL query with field quote but different for different databases. But not sure if it's right.

P.S. A new parameter in the MakeFields procedures was made with the default value for backward compatibility.

**Comment by silvioprog** [comment]
Hi @Al-Muhandis, thanks for reporting!

The PR sounds good. Possible improvements will be made via PR's comments. :+1:

**Comment by Al-Muhandis** [comment]
Hi @silvioprog , thanks for the answer!
I don't quite understand about what the comments were discussed, but added some comments directly in the PR code.

**Comment by silvioprog** [comment]
@Al-Muhandis sorry, I made a mistake. For some reason my comments were not sent. Please let me know if you received them now.

**Comment by Al-Muhandis** [comment]
Yes, I see now. I wrote there

**Comment by silvioprog** [comment]
Nice job dude! All changes was merged. Feel free to delete the temporary branch. Thank you!
