### ISSUE TITLE
Ambiguous units found - BrookLogger.pas

### ISSUE THREAD

**Issue by Al-Muhandis** [risoflora/brookfreepascal#13]
```
There are two units with the same name:

1. "C:\lazarus-stable\ccr\brookframework\Source\BrookLogger.pas" from BrookTardigrade 5.4.6
2. "C:\lazarus-stable\ccr\brookfreepascal\core\brooklogger.pas" from BrookRT 4.0
Both packages are connected. This means, either one package uses the other, or they are both used by a third package.
```
What do you recommend? Can this be tweaked at the library level?

**Comment by Al-Muhandis** [comment]
My long-standing project. There was no such window before

**Comment by Al-Muhandis** [comment]
[brook-bug.zip](https://github.com/risoflora/brookfreepascal/files/6135300/brook-bug.zip)
Minimal example. But it is just both package (BrookTardigrade and brookRT) in the project dependencies

**Comment by silvioprog** [comment]
Hi @Al-Muhandis, thanks for reporting!

I have been trying to understand the problem, but it seems related to the IDE. 😕

On Delphi, after adding two units with the same name to two distinct packages, the IDE doesn't report any error, however, on Lazarus, it raises the error you reported.

Anyway, I would appreciate any help to solve it.
