### ISSUE TITLE
Lazarus 2.0 error while to try run HTTPServer

### ISSUE THREAD

**Issue by Al-Muhandis** [risoflora/brookfreepascal#2]
Error not only in my projects, but also demo examples do not work. Very strange. Besides the fact that the Lazarus IDE has updated to 2.0 from 1.8.4, the Brook repositories was cloned from new places at https://github.com/risoflora/
Windows 10, Lazarus 2.0.0 32b, fpc 3.0.4
```
[Debugger Exception Notification]

Project project1 raised exception class 'EInvalidPointer' with message:
Cannot create server handle.

 In file 'C:\lazarus32\ccr\brookframework\Source\BrookHTTPServer.pas' at line 832:
InternalCreateServerHandle;
```

**Comment by silvioprog** [comment]
Hello @Al-Muhandis. Indeed, we should upgrade all packages/demos of brookfreepascal to Lazarus 2.0. (the same idea is applicable for brookframework).

This week I'm working to release Sagui 2.0 and after make a full upgrade in brookframework. (I'm working to fix https://github.com/risoflora/brookframework/issues/2 too, before releasing Sagui :wink:)

**Comment by Al-Muhandis** [comment]
Hello @silvioprog ! Thanks a lot. Although the previous error is not so important )

**Comment by Al-Muhandis** [comment]
I'm still trying to find the other characteristic features of the error.

**Comment by Al-Muhandis** [comment]
The same error with demo in brookframework (tardigrade) (not legacy)

**Comment by silvioprog** [comment]
It seems I sent accidentally some symbols of Sagui 2.0 when the repository was merged. 🤔 Could you test this attached patch? It is temporary, because the binding `libsagui.pas` will be upgraded as soon as Sagui 2.0 is release.

[0001-THIS-PATCH-IS-TEMPORARY.patch.txt](https://github.com/risoflora/brookfreepascal/files/2837936/0001-THIS-PATCH-IS-TEMPORARY.patch.txt)

**Comment by Al-Muhandis** [comment]
> 
> 
> It seems I sent accidentally some symbols of Sagui 2.0 when the repository was merged. 🤔 Could you test this attached patch? It is temporary, because the binding `libsagui.pas` will be upgraded as soon as Sagui 2.0 is release.
> 
> [0001-THIS-PATCH-IS-TEMPORARY.patch.txt](https://github.com/risoflora/brookfreepascal/files/2837936/0001-THIS-PATCH-IS-TEMPORARY.patch.txt)

Awesome! The problem is solved!

**Comment by silvioprog** [comment]
Great. :smiley: I'm going to keep this issue open as tip for other users. :-) (it will be closed automatically as soon as `libsagui.pas` is upgrade ...)

**Comment by silvioprog** [comment]
Fixed in https://github.com/risoflora/brookframework/commit/b2112487f9e178bdbd6489473c7e4aa758d53250. Thanks for reporting!
