### ISSUE TITLE
Install fails on fresh Lazarus 2.0.2

### ISSUE THREAD

**Issue by baeckerg** [risoflora/brookfreepascal#6]
I cannot install brookfreepascal or brookframework. The file BROOKMEDIATYPES.pas always results in

BrookMediaTypes.pas(331,21) Error: Illegal expression

Any idea what I do wrong? I use Win64

**Comment by silvioprog** [comment]
Hello @baeckerg . I'm going to try to reproduce the problem using this new Lazarus version and back with some feedback ...

**Comment by baeckerg** [comment]
Thanks - the Brookframework gave me the same issue but it went away with the recent update

**Comment by silvioprog** [comment]
Closing by already fixed. Thanks for testing/reporting! :-)
